import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const fontOpenSans = Open_Sans({ subsets: ["latin"] });
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import ToastProvider from "@/components/providers/ToastProvider";

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
       <html lang="en" suppressHydrationWarning>
        <body className={
          cn(fontOpenSans.className,'bg-white dark:bg-[#313338]')
        }>
          <ToastProvider/>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >

          {children}
          </ThemeProvider>

          </body>
      </html>
    </ClerkProvider>
  );
}
