import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const fontOpenSans = Open_Sans({ subsets: ["latin"] });
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={fontOpenSans.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
